FROM registry.cn-hangzhou.aliyuncs.com/shone-im/alpine:latest


ARG SERVER_NAME=task
ARG SERVER_TYPE=mq

ENV RUN_BIN bin/${SERVER_NAME}-${SERVER_TYPE}
ENV RUN_CONF /${SERVER_NAME}/conf/${SERVER_NAME}.yaml

RUN mkdir /$SERVER_NAME && mkdir /$SERVER_NAME/bin && mkdir /$SERVER_NAME/conf && mkdir -p /$SERVER_NAME/etc/conf

COPY ./bin/$SERVER_NAME-$SERVER_TYPE /$SERVER_NAME/bin/

COPY ./apps/$SERVER_NAME/$SERVER_TYPE/etc/dev/$SERVER_NAME.yaml /$SERVER_NAME/conf/

RUN chmod +x /$SERVER_NAME/bin/$SERVER_NAME-$SERVER_TYPE

WORKDIR /$SERVER_NAME

ENTRYPOINT $RUN_BIN -f $RUN_CONF
